[
 {
  "UberDateLog": "03/08/2021 06-56-44 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 23, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 06-57-12 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 23, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 07-43-20 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 28, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-06-30 PM",
  "UberLogs": [
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 47, in create_folder_structure\n    dirName = os.path.join(self.CreateBasePath, folderName)\nAttributeError: 'FolderFunction' object has no attribute 'CreateBasePath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-08-07 PM",
  "UberLogs": [
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 48, in create_folder_structure\n    dirName = os.path.join(self.CreateBasePath, folderName)\nAttributeError: 'FolderFunction' object has no attribute 'CreateBasePath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-09-19 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 26, in __init__\n    FolderConfigJSON = open('../Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: '../Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-10-19 PM",
  "UberLogs": [
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 48, in create_folder_structure\n    dirName = os.path.join(self.CreateBasePath, folderName)\nAttributeError: 'FolderFunction' object has no attribute 'CreateBasePath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-11-24 PM",
  "UberLogs": [
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 49, in create_folder_structure\n    dirName = os.path.join(self.CreateBasePath, folderName)\nAttributeError: 'FolderFunction' object has no attribute 'CreateBasePath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-12-09 PM",
  "UberLogs": [
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 57, in create_folder_structure\n    HTMLDirName = os.path.join(dirName, self.CreateHTMLFolder)\nAttributeError: 'FolderFunction' object has no attribute 'CreateHTMLFolder'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-14-41 PM",
  "UberLogs": [
   "ERROR: Required HTML and CSV file(s) cannot be copied in designated folders.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 82, in create_folder_structure\n    BuildHTMLPath = os.path.join(self.BuildPath, self.CreateHTMLFolder)\nAttributeError: 'FolderFunction' object has no attribute 'BuildPath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-16-59 PM",
  "UberLogs": [
   "ERROR: Required HTML and CSV file(s) cannot be copied in designated folders.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/FolderFunctions.py\", line 86, in create_folder_structure\n    BuildHTMLPath = os.path.join(self.BuildPath, self.CreateHTMLFolder)\nAttributeError: 'FolderFunction' object has no attribute 'BuildPath'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-18-16 PM",
  "UberLogs": [
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 118, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-21-19 PM",
  "UberLogs": [
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 118, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-22-33 PM",
  "UberLogs": [
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 118, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-26-08 PM",
  "UberLogs": [
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 118, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-27-03 PM",
  "UberLogs": [
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 118, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-29-08 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 4",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-31-17 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 2",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-55-45 PM",
  "UberLogs": [
   "ERROR: PDF file cannot be created, please check if the PDF file is already open!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pdfkit/pdfkit.py\", line 170, in to_pdf\n    with codecs.open(path, encoding='utf-8') as f:\n  File \"/home/manny/anaconda3/lib/python3.7/codecs.py\", line 904, in open\n    file = builtins.open(filename, mode, buffering)\nFileNotFoundError: [Errno 2] No such file or directory: '../cleaningrecord/Temp1source /home/manny/anaconda3/bin/activate/Cleaning-record-Temp1source /home/manny/anaconda3/bin/activate.pdf'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 258, in <module>\n    pdfkit.from_file(f\"{TemplatePath}/{FinalHTMLResult}\", GetCurrentPathName())\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pdfkit/api.py\", line 49, in from_file\n    return r.to_pdf(output_path)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pdfkit/pdfkit.py\", line 181, in to_pdf\n    '%s ' %(' '.join(args)),e)\nTypeError: not enough arguments for format string\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 09-56-40 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   [
    "Folder settings from folder_config.json Loaded successfully.",
    "CSV and HTML files copied successfully to the newly created designated folders.",
    "Folder Structure created successfully."
   ],
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 2",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-45-02 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 106, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\nNameError: name 'UberTripData' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-50-00 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 107, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/series.py\", line 4356, in apply\n    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1036, in apply\n    return self.apply_standard()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1095, in apply_standard\n    convert=self.convert_dtype,\n  File \"pandas/_libs/lib.pyx\", line 2859, in pandas._libs.lib.map_infer\n  File \"<string>\", line 1, in <lambda>\nNameError: name 'UberSplitDateTime' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-52-07 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 107, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/series.py\", line 4356, in apply\n    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1036, in apply\n    return self.apply_standard()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1095, in apply_standard\n    convert=self.convert_dtype,\n  File \"pandas/_libs/lib.pyx\", line 2859, in pandas._libs.lib.map_infer\n  File \"<string>\", line 1, in <lambda>\nNameError: name 'self' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-56-20 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 107, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/series.py\", line 4356, in apply\n    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1036, in apply\n    return self.apply_standard()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1095, in apply_standard\n    convert=self.convert_dtype,\n  File \"pandas/_libs/lib.pyx\", line 2859, in pandas._libs.lib.map_infer\n  File \"<string>\", line 1, in <lambda>\nNameError: name 'UberSplitDateTime' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-57-02 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 107, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/series.py\", line 4356, in apply\n    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1036, in apply\n    return self.apply_standard()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1095, in apply_standard\n    convert=self.convert_dtype,\n  File \"pandas/_libs/lib.pyx\", line 2859, in pandas._libs.lib.map_infer\n  File \"<string>\", line 1, in <lambda>\nNameError: name 'self' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 11-58-18 PM",
  "UberLogs": [
   "ERROR: Final DataFrame holding the Cleaning Records cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/DataFrameFunctions.py\", line 107, in create_final_df\n    final_df[v[\"dfColumn\"]] = eval(v[\"Value\"])\n  File \"<string>\", line 1, in <module>\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/series.py\", line 4356, in apply\n    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1036, in apply\n    return self.apply_standard()\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py\", line 1095, in apply_standard\n    convert=self.convert_dtype,\n  File \"pandas/_libs/lib.pyx\", line 2859, in pandas._libs.lib.map_infer\n  File \"<string>\", line 1, in <lambda>\nNameError: name 'UberSplitDateTime' is not defined\n",
   "Exiting the Program"
  ]
 }
]